from ultralytics import YOLO                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                         
# 验证：指标/统计图存到 /my/output/val_result/                                                                                                                                                                                                           
YOLO('/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/src/nn/yolo/runs/pose/yolo26s_pose_exchange12-4/weights/best.pt').val(                                                                                                                                                                                                                            
    # data='/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/src/nn/yolo/configs/exchange_pose_dataset.yaml',                                                                                                                                                                                                          
    data='/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/absolute/exchange_pose/rendered_assets_compose/dataset.yaml',            
    imgsz=640, device=0,                                                                                                                                                                                                                                 
    plots=True,                                                                                                                                                                                                                                          
    project='/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/absolute', name='val_result',                                                                                                                                                                                                             
)                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                         
# 预测：带框图存到 /my/output/pred/                                                                                                                                                                                                                      
YOLO('/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/src/nn/yolo/runs/pose/yolo26s_pose_exchange12-4/weights/best.pt').predict(                                                                                                                                                                                                                        
    source='test/*.png',                                                                                                                                                                                                                         
    save=True, imgsz=640, device=0,                                                                                                                                                                                                                      
    project='/mnt/workspace/RM2026-Engineer-Assembly-Algorithm/absolute', name='predict',                                                                                                                                                                                                                   
)                     